apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: simple-app-sample-app-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "36db466e-692a-4b4a-bcce-9a5354d54c40"
    keyvaultName: "privateaks-kv-dev"
    tenantId: "76b40f0e-dc42-4685-8fcc-75bcc8e3bff1"
    objects: |
      array:
        - |
          objectName: database-connection-string
          objectType: secret
        - |
          objectName: api-key
          objectType: secret
    resourceGroup: "privateaks-rg-dev"
    subscriptionId: "f9de1897-bc25-4f47-b8d9-1ff6c762767d"