{{- if .Values.secrets.enabled }}
# SecretProviderClass defines what secrets to sync from Azure Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sample-app.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ index .Values.workloadIdentity.serviceAccount.annotations "azure.workload.identity/client-id" | quote }}
    keyvaultName: {{ .Values.secrets.keyvault.name | quote }}
    cloudName: ""
    objects: |
      array:
        {{- range .Values.secrets.keyvault.secrets }}
        - |
          objectName: {{ .name | quote }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.secrets.keyvault.tenantId | quote }}
  
  secretObjects:
    - secretName: {{ include "sample-app.fullname" . }}-secrets
      type: Opaque
      data:
        {{- range .Values.secrets.keyvault.secrets }}
        - objectName: {{ .name | quote }}
          key: {{ .name | quote }}
        {{- end }}
{{- end }}
