{{- if .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ index .Values.workloadIdentity.serviceAccount.annotations "azure.workload.identity/client-id" }}
automountServiceAccountToken: true
{{- end }}